name: Lint Code with Pylint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Lint Python files
      run: |
        find . -name "*.py" -print0 | xargs -0 pylint
      # Detener el workflow si se encuentran errores
      continue-on-error: false
